pipeline {
    agent { label 'DockerAgent' } 
    environment {
        DOCKERHUB_CREDENTIALS = credentials('djtoler-dockerhub')
        PATH = "/home/ubuntu/.nvm/versions/node/v10.24.1/bin:$PATH"
    }
    
    stages {

        stage('TestFrontend') {
            steps {
                sh '''#!/bin/bash
                  rm -rf Deployment9
                  npx kill-port 3000
                  IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=DP9_Docker_Instance" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
                  echo "IP is ${IP}"
                  git clone https://github.com/djtoler/Deployment9
                  cd Dep9/frontend
                  npm install --save-dev @babel/plugin-proposal-private-property-in-object
                  npm ci
                  nohup npm start > frontend_start.txt &
                  sleep 30
                  grep "Compiled successfully!" frontend_start.txt
              '''
            }
        }

        stage('BuildFrontend') {
            steps {
              dir('Dep9/frontend') {
                sh 'pwd'
                sh 'docker build --no-cache -t djtoler/dp9frontend .'
              }
            }
        }

        stage('TestBackend') {
            steps {
              sh '''#!/bin/bash
               python3.9 -m venv test
               source test/bin/activate
               git clone https://github.com/djtoler/Deployment9
               cd Dep9/backend
               pip install pip --upgrade
               pip install -r requirements.tx
               pip install pytest
               py.test --verbose --junit-xml test-reports/results.xml
              '''
            }
            post {
                always {
                    junit 'test-reports/*.xml'
                }
            }
        }

        stage('BuildBackend') {
            steps {
              dir('Dep9/backend') {
                sh 'sudo docker build --no-cache -t djtoler/dp9backend .'
              }
            }
        }
        
        stage('DockerHubLogin') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        
        stage('PushFrontendDockerHub') {
            steps {
              dir('Dep9/frontend') {
                sh 'sudo docker push djtoler/dp9frontend'
              }
            }
        }

        stage('PushBackendDockerHub') {
            steps {
              dir('Dep9/backend') {
                sh 'sudo docker push djtoler/dp9backend'
              }
            }
        }
        
        stage('DeployBackend') {
            agent { label 'KubernetesAgent' }
            steps {
              dir('Dep9/backend') {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                    string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')
                ]) {
                    sh 'kubectl apply -f be_deployment.yaml && kubectl apply -f be_service.yaml' 
                }
              }
            }
        }
        
        stage('DeployFrontend') {
            agent { label 'KubernetesAgent' }
            steps {
              dir('Dep9/frontend') {
                withCredentials([
                    string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
                    string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')
                ]) {
                    sh 'kubectl apply -f fe_deployment.yaml && kubectl apply -f fe_service.yaml' 
                }
              }
            }
        }
    }
}

